# Generated by Django 4.1.13 on 2026-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assessment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='auto_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='pitch_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rhythm_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
