# Generated by Django 4.1.13 on 2026-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_submission_auto_feedback_submission_auto_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
