# Generated by Django 4.1.13 on 2026-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_submission_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pitch_plot',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_graphs/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rhythm_plot',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_graphs/'),
        ),
    ]
